In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in /opt/anaconda3/lib/python3.13/site-packages (2.0.0)
Requirement already satisfied: bleach in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (6.3.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (25.0)
Requirement already satisfied: protobuf in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (5.29.3)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.32.5)
Requirement already satisfied: tqdm in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/anaconda3/lib/python3.13/site-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /opt/anaconda3/lib/python3.13/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /opt/anaconda3/lib/python3.13/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests->kaggle) (2026.1.4)

In [2]:
# configuring the path of Kaggle.json file
!mkdir -p ~/.kaggle
!cp /Users/harshitdubey/Downloads/kaggle.json ~/.kaggle/

!chmod 600 ~/.kaggle/kaggle.json

In [3]:
!kaggle datasets download -d mlg-ulb/creditcardfraud

Dataset URL: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
License(s): DbCL-1.0
Downloading creditcardfraud.zip to /Users/harshitdubey
100%|██████████████████████████████████████| 66.0M/66.0M [00:07<00:00, 8.74MB/s]

In [4]:
!ls

anaconda_projects
ASS1_MSD_HARSHIT_250920.py
books-project
Breast Cancer Classification with Neural Network.ipynb
class_indices.json
creditcardfraud.zip
CUSTOMER SHOPPING ANALYSIS.ipynb
data
data.csv
Desktop
Documents
Downloads
dubey ji
EXERCISE 1.1(GROUP= B).ipynb
Face Mask Detection using CNN(Deep Learning System).ipynb
face-mask-dataset.zip
Group B.ipynb
HARSHIT DUBEY(PYTHON ASSIGNMENT).py
harshit.csv
HEART DISEASE PREDICTION MODEL.ipynb
Housing Price Prediction.ipynb
Library
LOAN PREDICTION MODEL.ipynb
MNIST Handwritten Digit Clasification using Deep Learning (Neural Network.ipynb
MNIST Handwritten Digit Clasification using Deep Learning (Neural Network).ipynb
Movies
Music
patient_data_sorted.dta
patient_data.csv
Pictures
PLANT DISEASE PREDICTION with CNN-DEEP LEARNING SYSTEM.ipynb
PLANT DISEASE PROJECT
plant_disease_prediction_model.h5
plantvillage dataset
plantvillage-dataset.zip
Public
PyCharmMiscProject
PYTHON ASSIGNMENT(ANJANI MISHRA).ipynb
r
r programming.18
r-programming
SHOPPING SALES ANALYSIS.ipynb
Sonar Rock vs Mine Prediction Model.ipynb
sonar_rock_mine_model.pkl
Untitled.html
Untitled.ipynb
Untitled.Rmd
Untitled1.ipynb
Untitled10-Copy1.ipynb
Untitled10.ipynb
Untitled11.ipynb
Untitled12.ipynb
Untitled13.ipynb
Untitled14.ipynb
Untitled2.ipynb
Untitled3.ipynb
Untitled4.ipynb
Untitled5.ipynb
Untitled6.ipynb
Untitled7.ipynb
Untitled8.ipynb
Untitled9.ipynb

In [5]:
## extracting the compessed Dataset
from zipfile import ZipFile
dataset = 'creditcardfraud.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

The dataset is extracted

In [6]:
!ls

anaconda_projects
ASS1_MSD_HARSHIT_250920.py
books-project
Breast Cancer Classification with Neural Network.ipynb
class_indices.json
creditcard.csv
creditcardfraud.zip
CUSTOMER SHOPPING ANALYSIS.ipynb
data
data.csv
Desktop
Documents
Downloads
dubey ji
EXERCISE 1.1(GROUP= B).ipynb
Face Mask Detection using CNN(Deep Learning System).ipynb
face-mask-dataset.zip
Group B.ipynb
HARSHIT DUBEY(PYTHON ASSIGNMENT).py
harshit.csv
HEART DISEASE PREDICTION MODEL.ipynb
Housing Price Prediction.ipynb
Library
LOAN PREDICTION MODEL.ipynb
MNIST Handwritten Digit Clasification using Deep Learning (Neural Network.ipynb
MNIST Handwritten Digit Clasification using Deep Learning (Neural Network).ipynb
Movies
Music
patient_data_sorted.dta
patient_data.csv
Pictures
PLANT DISEASE PREDICTION with CNN-DEEP LEARNING SYSTEM.ipynb
PLANT DISEASE PROJECT
plant_disease_prediction_model.h5
plantvillage dataset
plantvillage-dataset.zip
Public
PyCharmMiscProject
PYTHON ASSIGNMENT(ANJANI MISHRA).ipynb
r
r programming.18
r-programming
SHOPPING SALES ANALYSIS.ipynb
Sonar Rock vs Mine Prediction Model.ipynb
sonar_rock_mine_model.pkl
Untitled.html
Untitled.ipynb
Untitled.Rmd
Untitled1.ipynb
Untitled10-Copy1.ipynb
Untitled10.ipynb
Untitled11.ipynb
Untitled12.ipynb
Untitled13.ipynb
Untitled14.ipynb
Untitled2.ipynb
Untitled3.ipynb
Untitled4.ipynb
Untitled5.ipynb
Untitled6.ipynb
Untitled7.ipynb
Untitled8.ipynb
Untitled9.ipynb


# Importing the Dependencies

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [10]:
df = pd.read_csv("creditcard.csv")

In [11]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [13]:
df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [14]:
df.head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
6,4.0,1.229658,0.141004,0.045371,1.202613,0.191881,0.272708,-0.005159,0.081213,0.464960,...,-0.167716,-0.270710,-0.154104,-0.780055,0.750137,-0.257237,0.034507,0.005168,4.99,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
8,7.0,-0.894286,0.286157,-0.113192,-0.271526,2.669599,3.721818,0.370145,0.851084,-0.392048,...,-0.073425,-0.268092,-0.204233,1.011592,0.373205,-0.384157,0.011747,0.142404,93.20,0
9,9.0,-0.338262,1.119593,1.044367,-0.222187,0.499361,-0.246761,0.651583,0.069539,-0.736727,...,-0.246914,-0.633753,-0.120794,-0.385050,-0.069733,0.094199,0.246219,0.083076,3.68,0

In [15]:
# dataset informations
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [17]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [20]:
# distribution of legit transactions & fraudulent transactions
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

# 0 = legit/normal transaction (safe transaction)
# 1 = fraud/ fake transaction

In [21]:
# separating the data for analysis
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [22]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [23]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [24]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [26]:
# compare the values for both transactions
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Under-Sampling

In [27]:
legit_sample = legit.sample(n=492)  ##normal transaction me se 492 random row select kernge

Concatenating two DataFrames

In [28]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)   ## 492 normal + 492 fraud ko add kerke rahe

In [29]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
188562,128028.0,2.039973,-1.444355,-1.973415,-1.857694,1.250826,3.685726,-1.554068,0.938900,-0.037217,...,0.355901,0.873989,0.124381,0.744427,-0.131516,-0.073300,0.019541,-0.044390,69.00,0
145568,87057.0,2.042990,-0.118762,-1.313449,0.218218,0.242798,-0.502417,0.113318,-0.158220,0.305571,...,-0.219678,-0.469949,0.213657,-0.528473,-0.163695,0.290763,-0.072506,-0.078086,3.66,0
105694,69650.0,0.988943,-0.268341,1.308022,1.668857,-0.775645,0.812293,-0.617338,0.420991,0.993633,...,-0.341337,-0.588456,0.083384,0.229288,0.358252,-0.541228,0.083704,0.023408,27.99,0
248695,154052.0,2.050365,-0.118267,-1.374097,0.184951,0.077944,-0.841839,0.056083,-0.187798,0.488444,...,0.283022,0.924813,-0.044445,-0.314024,0.246446,-0.099457,-0.024200,-0.072283,1.00,0
139173,83047.0,-0.369235,0.935610,1.931349,0.067966,-0.233516,-1.167958,0.921590,-0.304801,-0.241616,...,-0.243692,-0.495744,0.025837,0.889619,-0.298895,0.010539,0.097879,-0.096742,10.48,0

In [30]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [31]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [32]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93890.008130,0.083753,0.053246,0.007905,0.037384,0.074375,0.001241,0.054194,-0.003561,0.063200,...,-0.049251,-0.018717,0.019605,0.001913,-0.045867,0.034850,0.012625,0.033406,0.010995,77.679675
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321


Splitting the data into Features & Targets

In [33]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [34]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
188562  128028.0  2.039973 -1.444355 -1.973415 -1.857694  1.250826  3.685726
145568   87057.0  2.042990 -0.118762 -1.313449  0.218218  0.242798 -0.502417
105694   69650.0  0.988943 -0.268341  1.308022  1.668857 -0.775645  0.812293
248695  154052.0  2.050365 -0.118267 -1.374097  0.184951  0.077944 -0.841839
139173   83047.0 -0.369235  0.935610  1.931349  0.067966 -0.233516 -1.167958
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
188562 -1.554068  0.938900 -0.037217  ...  0.165531  0.355901  0.873989
145568  0.113318 -0.158220  0.305571  ... -0.187289 -0.219678 -0.469949
105694 -0.617338  0.420991  0.993633  ... -0.176705 -0.341337 -0.588456
248695  0.056083 -0.187798  0.488444  ... -0.262022  0.283022  0.924813
139173  0.921590 -0.304801 -0.241616  ...  0.147802 -0.243692 -0.495744
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
188562  0.124381  0.744427 -0.131516 -0.073300  0.019541 -0.044390   69.00
145568  0.213657 -0.528473 -0.163695  0.290763 -0.072506 -0.078086    3.66
105694  0.083384  0.229288  0.358252 -0.541228  0.083704  0.023408   27.99
248695 -0.044445 -0.314024  0.246446 -0.099457 -0.024200 -0.072283    1.00
139173  0.025837  0.889619 -0.298895  0.010539  0.097879 -0.096742   10.48
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [35]:
print(Y)

188562    0
145568    0
105694    0
248695    0
139173    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

# Split the data into Training data & Testing Data

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [37]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

# Model Training

Logistic Regression

In [39]:
model = LogisticRegression()

In [40]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

/opt/anaconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [41]:
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

LogisticRegression(multi_class='auto')

Model Evaluation

Accuracy Score

In [42]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [43]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.940279542566709

In [44]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [47]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9289340101522843

## Model gives around 93% accuracy with balanced dataset and shows good generalization.

In [48]:
from sklearn.metrics import classification_report

print(classification_report(Y_test, X_test_prediction))

              precision    recall  f1-score   support

           0       0.90      0.96      0.93        99
           1       0.96      0.90      0.93        98

    accuracy                           0.93       197
   macro avg       0.93      0.93      0.93       197
weighted avg       0.93      0.93      0.93       197

 Class 0 (Normal)
Precision = 0.90
👉 Jab model bolta hai “Normal”
→ 90% baar sahi hota hai

Recall = 0.96
👉 Actual normal transactions me se
→ 96% correctly identify kiya

Class 1 (Fraud) (MOST IMPORTANT)
Precision = 0.96
👉 Jab model bolta hai “Fraud”
→ 96% baar sahi hai ✅

Recall = 0.90 🚨
👉 Actual fraud me se:
Plain text
90% detect kiya  
10% miss kar diya ❌
👉 Ye sabse important metric hai fraud detection me